import { TemplatePage } from "../TemplatePage";

const body = "\u003cheader\u003e\r\n        \u003ca href=\"/\" class=\"logo\"\u003eFresh Market\u003c/a\u003e\r\n    \u003c/header\u003e\r\n    \u003cmain class=\"container\"\u003e\r\n        \u003cdiv class=\"card\"\u003e\r\n            \u003cdiv class=\"card-header\"\u003e\r\n                \u003ch2\u003eSign in\u003c/h2\u003e\r\n            \u003c/div\u003e\r\n            \u003cdiv class=\"card-body\"\u003e\r\n                \u003cp th:if=\"${error}\" th:text=\"${error}\" class=\"text-muted\"\u003e\u003c/p\u003e\r\n                \u003cp th:if=\"${param.logout}\" class=\"text-muted\"\u003eYou have been signed out.\u003c/p\u003e\r\n                \u003cform th:if=\"${otpSent == null}\" th:action=\"@{/login/request-otp}\" method=\"post\"\u003e\r\n                    \u003cinput type=\"hidden\" th:name=\"${_csrf.parameterName}\" th:value=\"${_csrf.token}\"\u003e\r\n                    \u003cdiv class=\"form-group\"\u003e\r\n                        \u003clabel for=\"phone\"\u003eMobile number\u003c/label\u003e\r\n                        \u003cinput type=\"tel\" id=\"phone\" name=\"phone\" class=\"form-control\" required autofocus\u003e\r\n                    \u003c/div\u003e\r\n                    \u003cbutton type=\"submit\" class=\"btn\"\u003eSend OTP\u003c/button\u003e\r\n                \u003c/form\u003e\r\n                \u003cdiv class=\"form-footer\"\u003e\r\n                    \u003cp\u003eOr use Clerk authentication:\u003c/p\u003e\r\n                    \u003ca class=\"btn\" href=\"/clerk-login\"\u003eContinue with Clerk\u003c/a\u003e\r\n                \u003c/div\u003e\r\n                \u003cform th:if=\"${otpSent}\" th:action=\"@{/login/verify-otp}\" method=\"post\"\u003e\r\n                    \u003cinput type=\"hidden\" th:name=\"${_csrf.parameterName}\" th:value=\"${_csrf.token}\"\u003e\r\n                    \u003cinput type=\"hidden\" name=\"phone\" th:value=\"${phone}\"\u003e\r\n                    \u003cdiv class=\"form-group\"\u003e\r\n                        \u003clabel for=\"otp\"\u003eOne-time password\u003c/label\u003e\r\n                        \u003cinput type=\"text\" id=\"otp\" name=\"otp\" class=\"form-control\"\r\n                               inputmode=\"numeric\" pattern=\"[0-9]{6}\" maxlength=\"6\" required autofocus\u003e\r\n                    \u003c/div\u003e\r\n                    \u003cbutton type=\"submit\" class=\"btn\"\u003eVerify and continue\u003c/button\u003e\r\n                \u003c/form\u003e\r\n            \u003c/div\u003e\r\n        \u003c/div\u003e\r\n    \u003c/main\u003e";
const assets: string[] = ["link:/css/register.css"];

export function LoginPage() {
  return <TemplatePage body={body} assets={assets} />;
}

